import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/providers/providers';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import { Flex } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Flex
						minH={'6xl'}
						direction={'column'}
						justifyContent={'space-between'}>
						<Flex w={'auto'} direction={'column'} minH={'auto'}>
							<Navbar />
							{children}
						</Flex>

						{/* This is Footer */}
						<Footer />
					</Flex>
				</Providers>
			</body>
		</html>
	);
}
